<?xml version="1.0" encoding="utf-8"?>
<project  xmlns:ivy="antlib:org.apache.ivy.ant" name="marc4j" default="jar" basedir="." 
     xmlns:if="ant:if" xmlns:unless="ant:unless">

    <target name="init">
        <tstamp />
       <!-- <record name="build.log" loglevel="verbose" append="no" /> -->
    </target>

    <property file="build.properties" />
    <property environment="env" /> 

    <tstamp>
        <format property="TODAY" pattern="yyyy-MM-dd HH:mm:ss Z" timezone="GMT" />
    </tstamp>

    <target name="prepare" depends="init,setup-ivy" unless="prepared">
        <mkdir dir="${build.dir}" />
        <mkdir dir="${build.classes.dir}"/>
        <mkdir dir="${build.test-classes.dir}"/>
        <mkdir dir="${build.generated-src.dir}"/>
        <mkdir dir="${lib.dir}"/>
        <ivy:retrieve />
        <!-- Add the downloaded ant-contrib JAR to the classpath -->
        <taskdef resource="net/sf/antcontrib/antlib.xml">
            <classpath>
                <fileset dir="lib">
                    <include name="ant-contrib-*.jar" />
                </fileset>
            </classpath>
        </taskdef>
        <property name="prepared" value="true"/>
    </target>

    <path id="classpath">
        <fileset dir="${lib.dir}">
            <include name="**/*.jar" />
        </fileset>
    </path>

    <path id="test.classpath">
        <pathelement location="${build.classes.dir}" />
        <pathelement location="${build.test-classes.dir}" />
        <pathelement location="test/resources"/>
        <fileset dir="${lib.dir}">
            <include name="**/*.jar" />
            <exclude name="**/ant*.jar" />
        </fileset>
    </path>

    <target name="prepare-codetablegen" depends="prepare">
        <mkdir dir="${build.generated-src.dir}/org/marc4j/converter/impl" />
        <dependset>
            <srcfileset  dir="${src.dir}/org/marc4j/converter/impl/"/>
            <targetfileset dir="${build.generated-src.dir}/org/marc4j/converter/impl/" includes="*.java"/>
        </dependset>
        <available file="${build.generated-src.dir}/org/marc4j/converter/impl/CodeTableGenerated.java" property="already.ctged"/>
    </target>

    <target name="codetablegen" depends="prepare-codetablegen" unless="already.ctged">
        <java fork="true" classname="org.marc4j.converter.impl.CodeTableGenerator" errorproperty="CodeTableGenerated.error" output="${build.generated-src.dir}/org/marc4j/converter/impl/CodeTableGenerated.java" >
            <classpath location="${build.classes.dir}" />
            <arg value="MARC8"/>
        </java>
        <java fork="true" classname="org.marc4j.converter.impl.ReverseCodeTableGenerator" errorproperty="ReverseCodeTableGenerated.error" output="${build.generated-src.dir}/org/marc4j/converter/impl/ReverseCodeTableGenerated.java" >
            <classpath location="${build.classes.dir}" />
            <arg value="MARC8"/>
        </java>
        <java fork="true" classname="org.marc4j.converter.impl.CodeTableGenerator" errorProperty="UnimarcCodeTableGenerated.error" output="${build.generated-src.dir}/org/marc4j/converter/impl/UnimarcCodeTableGenerated.java" >
            <classpath location="${build.classes.dir}" />
            <arg value="UNIMARC"/>
        </java>
        <java fork="true" classname="org.marc4j.converter.impl.ReverseCodeTableGenerator" errorProperty="UnimarcReverseCodeTableGenerated.error" output="${build.generated-src.dir}/org/marc4j/converter/impl/UnimarcReverseCodeTableGenerated.java" >
            <classpath location="${build.classes.dir}" />
            <arg value="UNIMARC"/>
        </java>
    </target>

    <target name="compile-codegen" depends="codetablegen">
        <javac encoding="UTF-8" srcdir="${build.generated-src.dir}" destdir="${build.classes.dir}" includes="**/*Generated.java" debug="false">
            <classpath refid="classpath" />
        </javac>

    </target>
    <target name="compile-all" depends="compile-base,compile-codegen"/>

    <target name="compile-base" depends="prepare">
        <javac encoding="UTF-8" srcdir="${src.dir}" destdir="${build.classes.dir}" includes="**/*.java" excludes="**/*Generated.java" debug="true" debuglevel="source,lines,vars">
            <classpath refid="classpath" />
        </javac>
        <copy todir="${build.classes.dir}">
            <fileset dir="${src.dir}">
                <include name="**/*.properties" />
                <include name="**/*.xml" />
                <exclude name="**/tests/*" />
                <exclude name="**/tests" />
            </fileset>
        </copy>
    </target>

    <target name="compile-tests" depends="compile-all">
        <javac encoding="UTF-8" srcdir="${test.src.dir}" destdir="${build.test-classes.dir}" includes="**/*.java" excludes="**/*Generated.java" debug="true" debuglevel="source,lines,vars">
            <classpath refid="test.classpath" />
        </javac>
    </target>

    <target name="test" depends="compile-all,compile-tests">
        <junit fork="yes" forkmode="perBatch" haltonfailure="false">
        	<jvmarg value="-Dfile.encoding=UTF-8"/>
        	<batchtest>
                <fileset dir="${test.src.dir}">
                    <exclude name="org/marc4j/test/utils/**"/>
                </fileset>
            </batchtest>
            <formatter type="brief" usefile="false" />
            <classpath refid="test.classpath" />
        </junit>
    </target>

    <target name="jar" depends="compile-all,version">
        <jar jarfile="${build.dir}/${jar.name}">
            <manifest>
                <attribute name="Main-Class" value="org.marc4j.util.UtilDriver"/>
                <attribute name="Version" value="${version}"/>
                <attribute name="Built-Date" value="${TODAY}"/>
                <section name="org/marc4j">
                  <attribute name="Specification-Title" value="marc4j"/>
                  <attribute name="Specification-Version" value="${specversion}"/>
                  <attribute name="Specification-Vendor" value="org.marc4j"/>

                  <attribute name="Implementation-Title" value="marc4j"/>
                  <attribute name="Implementation-Version" value="${version}"/>
                  <attribute name="Implementation-Vendor" value="Team marc4j"/>
                </section>
            </manifest>
            <fileset dir="${build.classes.dir}">
                <include name="**/*.class" />
                <exclude name="**/CodeTableGenerator.class" />
                <exclude name="**/ReverseCodeTableGenerator.class" />
                <exclude name="**/samples/**/*.*" />
                <exclude name="**/solrmarc/**/*.class" />
                <exclude name="**/test/**/*.*" />
                <include name="**/*.properties" />
                <exclude name="**/*.xml" />
            </fileset>
        </jar>
    </target>

    <target name="javadoc" depends="prepare" unless="javadoc.already.run" >
        <mkdir dir="${apidoc.dir}" />
        <javadoc encoding="UTF-8" charset="UTF-8" docencoding="UTF-8" destdir="${apidoc.dir}" author="true" version="true" overview="overview.html" use="true" windowtitle="MARC4J API" doctitle="MARC4J API" bottom="Copyright &#169; 2002-2006 Bas Peters. All Rights Reserved.">
            <packageset dir="${src.dir}" defaultexcludes="yes">
                <exclude name="org/marc4j/samples" />
                <exclude name="org/marc4j/test" />
            </packageset>
            <classpath refid="classpath" />
            <link offline="true" href="http://java.sun.com/products/jdk/1.6/docs/api/" packagelistLoc="." />
        </javadoc>
        <property name="javadoc.already.run" value="true" />
    </target>

    <target name="clean" depends="init">
        <delete includeEmptyDirs="true">
            <fileset dir="${dist.dir}" includes="**/*" defaultexcludes="no"/>
        </delete>
        <delete dir="${build.dir}" />
    </target>

    <target name="distclean" depends="clean">
        <delete dir="${lib.dir}"/>
        <delete dir="${ivy.jar.dir}"/>

    </target>

    <target name="dist" depends="jar,javadoc" unless="dist.already.run" >
        <delete dir="${dist.dir}" includes="*" />
        <property name="prefix" value="${project.name}-${version}" />
        <property name="tmp.dir" value="${dist.dir}/tmp" />
        <property name="tmp.arc.dir" value="${tmp.dir}/${prefix}" />
        <property name="dist.arc" value="${dist.dir}/${prefix}" />
        <mkdir dir="${tmp.arc.dir}" />
        <copy file="${build.dir}/${jar.name}" tofile="${dist.dir}/${jar.name}" overwrite="true" />
        <copy file="${basedir}/pom_template.xml" tofile="${dist.dir}/${project.name}-${version}.pom" overwrite="true" >
            <filterchain>
                <replacetokens>
                    <token key="VERSION" value="${version}"/>
                </replacetokens>
            </filterchain>
        </copy>
        <copy todir="${tmp.arc.dir}">
            <fileset dir=".">
                <include name="LICENSE.*" />
                <include name="build.*" />
                <exclude name="*.log" />
                <include name="*.jar" />
                <include name="*.html" />
            </fileset>
        </copy>
        <copy todir="${tmp.arc.dir}" file="${build.dir}/${jar.name}"/>

        <copy todir="${tmp.arc.dir}/${src.dir}">
            <fileset dir="${src.dir}" >
                <exclude name="**/CodeTableGenerated.java" />
            </fileset>
        </copy>

        <copy todir="${tmp.arc.dir}/${test.src.dir}">
            <fileset dir="${test.src.dir}" >
            </fileset>
        </copy>

        <copy todir="${tmp.arc.dir}/${lib.dir}">
            <fileset dir="${lib.dir}">
                <exclude name="junit*.jar" />
            </fileset>
        </copy>
        <copy todir="${tmp.arc.dir}/apidoc">
            <fileset dir="${apidoc.dir}" />
        </copy>
        <tar tarfile="${dist.arc}.tar" basedir="${tmp.arc.dir}" />
        <gzip zipfile="${dist.arc}.tar.gz" src="${dist.arc}.tar" />
        <delete file="${dist.arc}.tar" />
        <delete file="${dist.arc}.zip" />
        <zip compress="true" basedir="${tmp.dir}" zipfile="${dist.arc}.zip" />
        <delete dir="${tmp.dir}" />
        <jar jarfile="${dist.dir}/${jar.javadoc.name}">
            <manifest>
                <section name="org/marc4j">
                  <attribute name="Specification-Title" value="marc4j"/>
                  <attribute name="Specification-Version" value="${specversion}"/>
                  <attribute name="Specification-Vendor" value="org.marc4j"/>

                  <attribute name="Implementation-Title" value="marc4j"/>
                  <attribute name="Implementation-Version" value="${version}"/>
                  <attribute name="Implementation-Vendor" value="Team marc4j"/>
                </section>
            </manifest>
            <fileset dir="${apidoc.dir}">
                <include name="**" />
            </fileset>
        </jar>
        <jar jarfile="${dist.dir}/${jar.sources.name}" >
            <manifest>
                <section name="org/marc4j">
                  <attribute name="Specification-Title" value="marc4j"/>
                  <attribute name="Specification-Version" value="${specversion}"/>
                  <attribute name="Specification-Vendor" value="org.marc4j"/>

                  <attribute name="Implementation-Title" value="marc4j"/>
                  <attribute name="Implementation-Version" value="${version}"/>
                  <attribute name="Implementation-Vendor" value="Team marc4j"/>
                </section>
            </manifest>
            <fileset dir="${src.dir}">
                <include name="**/*.java" />
                <exclude name ="**/samples/**" />
            </fileset>
            <fileset dir="${build.generated-src.dir}">
                <include name="**/*.java" />
            </fileset>
        </jar>
        <property name="dist.already.run" value="true" />
    </target>

    <!--
        =====================================================================
        Sonatype Central Publishing Portal release chain.

        This replaces the old oss.sonatype.org / Nexus staging flow
        (formerly: sign, upload, close-staging-repo, wait-closed, promote,
        release-ready, sonatype-release targets, now removed). That legacy
        host has been sunset by Sonatype in favor of Central Publishing;
        see https://central.sonatype.org/publish/publish-portal-api/

        Chain: dist -> sonatype-package -> central-upload ->
               central-wait-validated -> central-publish (= central-release)

        Two independent sets of prerequisites are checked separately,
        since they're needed at different stages and by different people/
        machines in practice (packaging/signing can happen anywhere gpg
        is set up; upload only needs curl and a Central user token):

          - package-ready: gpg is available and gpg-passphrase is set
            (needed by sonatype-package's signing step)
          - central-release-ready: curl is available and
            central.bearer.token is set (needed by central-upload/
            central-wait-validated/central-publish)
        =====================================================================
    -->

    <target name="package-ready" depends="prepare" unless="package.is.ready">
        <!--
            Do NOT use <available filepath="${env.PATH}">: on Windows the
            PATH env var is very often actually named "Path" (or some
            other casing), not "PATH", and Ant property lookups are case
            sensitive, so ${env.PATH} can silently fail to resolve even
            when gpg genuinely is on PATH. searchpath="true" on <exec>
            delegates the PATH search to the OS process-launch mechanism
            itself, which is properly case-insensitive on Windows.
        -->
        <exec executable="gpg" searchpath="true" resultproperty="gpg.probe.exit" failonerror="false" failifexecutionfails="false">
            <arg value="--version" />
        </exec>
        <condition property="has-gpg">
            <equals arg1="${gpg.probe.exit}" arg2="0" />
        </condition>

        <if>
            <and>
                <not>
                    <isset property="is.snapshot" />
                </not>
                <isset property="gpg-passphrase" />
                <isset property="has-gpg" />
            </and>
            <then>
                <property name="package.is.ready" value="true" />
            </then>
            <else>
                <echo if:set="is.snapshot"                message="ERROR: current state is snapshot" level="error" />
                <echo unless:set="gpg-passphrase"         message="ERROR: gpg passphrase not provided (pass -Dgpg-passphrase=...)" level="error" />
                <echo if:blank="${gpg-passphrase}"        message="ERROR: gpg passphrase is blank" level="error" />
                <echo unless:set="has-gpg"                message="ERROR: gpg not found on PATH" level="error" />
                <fail message="required values for signing a Sonatype release package not all defined" />
            </else>
        </if>
    </target>

    <target name="sonatype-package" description="Creates the uploadable Sonatype Central bundle (checksummed, signed, correctly laid out)" depends="dist,package-ready" unless="sonatype-package.already.run">

        <property name="pom.name" value="${project.name}-${version}.pom" />

        <!-- The four artifacts Central requires checksums/signatures for -->
        <fileset id="artifacts.to.package" dir="${dist.dir}">
            <include name="${jar.name}" />
            <include name="${jar.sources.name}" />
            <include name="${jar.javadoc.name}" />
            <include name="${pom.name}" />
        </fileset>

        <echo message="Generate sha1 files" />
        <checksum algorithm="SHA-1" fileext=".sha1" todir="${dist.dir}">
            <fileset refid="artifacts.to.package" />
        </checksum>

        <echo message="Generate md5 files" />
        <checksum algorithm="MD5" fileext=".md5" todir="${dist.dir}">
            <fileset refid="artifacts.to.package" />
        </checksum>

        <echo message="Generate PGP signatures (.asc) using gpg" />
        <delete dir="${dist.dir}" includes="*.asc" />
        <exec executable="gpg" dir="${dist.dir}" searchpath="true" >
            <arg value="--batch" />
            <arg value="-a" />
            <arg value="--pinentry-mode=loopback" />
            <arg value="--passphrase" />
            <arg value="${gpg-passphrase}" />
            <arg value="--detach-sign" />
            <arg value="${jar.name}" />
        </exec>
        <exec executable="gpg" dir="${dist.dir}" searchpath="true" >
            <arg value="--batch" />
            <arg value="-a" />
            <arg value="--pinentry-mode=loopback" />
            <arg value="--passphrase" />
            <arg value="${gpg-passphrase}" />
            <arg value="--detach-sign" />
            <arg value="${jar.sources.name}" />
        </exec>
        <exec executable="gpg" dir="${dist.dir}" searchpath="true" >
            <arg value="--batch" />
            <arg value="-a" />
            <arg value="--pinentry-mode=loopback" />
            <arg value="--passphrase" />
            <arg value="${gpg-passphrase}" />
            <arg value="--detach-sign" />
            <arg value="${jar.javadoc.name}" />
        </exec>
        <exec executable="gpg" dir="${dist.dir}" searchpath="true" >
            <arg value="--batch" />
            <arg value="-a" />
            <arg value="--pinentry-mode=loopback" />
            <arg value="--passphrase" />
            <arg value="${gpg-passphrase}" />
            <arg value="--detach-sign" />
            <arg value="${pom.name}" />
        </exec>
        <available file="${dist.dir}/${jar.name}.asc" property="sonatype-package.sign.successful" />
        <fail unless="sonatype-package.sign.successful" message="failure signing artifacts; central bundle would be rejected" />

        <echo message="Generate bundle file for Sonatype" />
        <zip destfile="${dist.dir}/central-bundle-${version}.zip" >
            <!--
                groupId=org.marc4j -> "org/marc4j", then artifactId
                "marc4j", then version - matches real Maven repository
                layout (groupId-as-path/artifactId/version/). Adjust the
                "marc4j" segment below if pom_template.xml's actual
                groupId/artifactId ever differ.
            -->
            <zipfileset prefix="org/marc4j/marc4j/${version}" dir="${dist.dir}">
                <include name="marc4j*.jar"/>
                <include name="marc4j*.pom"/>
                <include name="marc4j*.sha1"/>
                <include name="marc4j*.md5"/>
                <include name="marc4j*.asc"/>
            </zipfileset>
        </zip>
        <property name="sonatype-package.already.run" value="true" />
    </target>

    <!--
        One-time manual setup required before central-upload will work:

          1. Log in at https://central.sonatype.com and generate a
             "User Token" (Account -> Generate User Token). This gives
             you a tokenUsername/tokenPassword pair - not your login
             password.

          2. Base64-encode "tokenUsername:tokenPassword" yourself, once:

               printf "tokenUsername:tokenPassword" | base64

          3. Supply the resulting string as -Dcentral.bearer.token=... on
             the ant command line. Despite the API calling this a
             "Bearer" token, the value is just that base64 string -
             Central's own docs use the same convention.
    -->
    <target name="central-release-ready" depends="prepare" unless="central.release.is.ready">
        <exec executable="curl" searchpath="true" resultproperty="curl.probe.exit" failonerror="false" failifexecutionfails="false">
            <arg value="--version" />
        </exec>
        <condition property="has-curl">
            <equals arg1="${curl.probe.exit}" arg2="0" />
        </condition>

        <if>
            <and>
                <not>
                    <isset property="is.snapshot" />
                </not>
                <isset property="central.bearer.token" />
                <isset property="has-curl" />
            </and>
            <then>
                <property name="central.release.is.ready" value="true" />
            </then>
            <else>
                <echo if:set="is.snapshot"                    message="ERROR: current state is snapshot" level="error" />
                <echo unless:set="central.bearer.token"       message="ERROR: central.bearer.token not provided (see comment above central-release-ready target)" level="error" />
                <echo if:blank="${central.bearer.token}"      message="ERROR: central.bearer.token is blank" level="error" />
                <echo unless:set="has-curl"                   message="ERROR: curl not found on PATH" level="error" />
                <fail message="required values for a Central Publishing Portal release not all defined" />
            </else>
        </if>
    </target>

    <!--
        Uploads the bundle zip built by sonatype-package. Defaults to
        publishingType=USER_MANAGED (upload + validate only; you then log
        in to central.sonatype.com/publishing to click "Publish" yourself).
        Pass -Dcentral.publishing.type=AUTOMATIC to auto-publish once
        validation passes, skipping the manual click.
    -->
    <target name="central-upload" depends="sonatype-package,central-release-ready" if="central.release.is.ready" unless="is.snapshot">
        <property name="central.publishing.type" value="USER_MANAGED" />
        <echo message="Uploading central-bundle-${version}.zip to Central Publishing Portal (publishingType=${central.publishing.type})" />
        <exec executable="curl" outputproperty="central.upload.output" errorproperty="central.upload.error.output" failonerror="false">
            <arg value="--silent" />
            <arg value="--show-error" />
            <arg value="--request" />
            <arg value="POST" />
            <arg value="--header" />
            <arg value="Authorization: Bearer ${central.bearer.token}" />
            <arg value="--form" />
            <arg value="bundle=@${dist.dir}/central-bundle-${version}.zip" />
            <arg value="https://central.sonatype.com/api/v1/publisher/upload?name=${project.name}-${version}&amp;publishingType=${central.publishing.type}" />
        </exec>
        <echo message="upload response = ${central.upload.output}" />
        <condition property="central.deploymentId" value="${central.upload.output}">
            <!-- a successful response body is just the bare deploymentId, nothing else -->
            <matches pattern="^[a-fA-F0-9-]{20,}$" string="${central.upload.output}" />
        </condition>
        <fail unless="central.deploymentId" message="Upload to Central Publishing Portal didn't return a deployment id.${line.separator}Response: ${central.upload.output}${line.separator}Error: ${central.upload.error.output}" />
        <echo message="deploymentId = ${central.deploymentId}" />
    </target>

    <!--
        Polls /api/v1/publisher/status until the deployment reaches
        VALIDATED (success - stops here for USER_MANAGED, since publishing
        then requires the explicit central-publish target below) or
        PUBLISHED (success, for AUTOMATIC publishingType), or FAILED
        (build fails immediately so CI surfaces the problem).
    -->
    <target name="central-wait-validated" depends="central-upload" if="central.deploymentId">
        <for list="1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20" param="loop-count">
            <sequential>
                <if>
                    <not>
                        <or>
                            <isset property="central.state.terminal" />
                        </or>
                    </not>
                    <then>
                        <echo message="sleeping ..." />
                        <sleep seconds="15" />
                        <echo message="Checking deployment status, attempt @{loop-count} ..." />
                        <local name="central.status.output" />
                        <exec executable="curl" outputproperty="central.status.output" failonerror="false">
                            <arg value="--silent" />
                            <arg value="--request" />
                            <arg value="POST" />
                            <arg value="--header" />
                            <arg value="Authorization: Bearer ${central.bearer.token}" />
                            <arg value="https://central.sonatype.com/api/v1/publisher/status?id=${central.deploymentId}" />
                        </exec>
                        <echo message="status response = ${central.status.output}" />

                        <condition property="central.state.terminal">
                            <or>
                                <contains string="${central.status.output}" substring="&quot;deploymentState&quot;:&quot;VALIDATED&quot;" />
                                <contains string="${central.status.output}" substring="&quot;deploymentState&quot;:&quot;PUBLISHED&quot;" />
                                <contains string="${central.status.output}" substring="&quot;deploymentState&quot;:&quot;FAILED&quot;" />
                            </or>
                        </condition>
                        <condition property="central.state.failed">
                            <contains string="${central.status.output}" substring="&quot;deploymentState&quot;:&quot;FAILED&quot;" />
                        </condition>
                    </then>
                </if>
            </sequential>
        </for>

        <fail unless="central.state.terminal" message="Central deployment ${central.deploymentId} did not reach a terminal state after repeated checks; check https://central.sonatype.com/publishing/deployments" />
        <fail if="central.state.failed" message="Central deployment ${central.deploymentId} FAILED validation; check https://central.sonatype.com/publishing/deployments for details (do not drop the deployment if you need Sonatype support's help diagnosing it)" />
        <echo message="Deployment ${central.deploymentId} reached a successful terminal state." />
    </target>

    <!--
        Only relevant when central.publishing.type=USER_MANAGED (the
        default above): explicitly moves a VALIDATED deployment to
        PUBLISHING. If you used publishingType=AUTOMATIC on upload, this
        target is unnecessary - Central does this step itself.
    -->
    <target name="central-publish" depends="central-wait-validated" if="central.deploymentId" unless="central.state.failed">
        <echo message="Publishing deployment ${central.deploymentId}" />
        <exec executable="curl" outputproperty="central.publish.output" errorproperty="central.publish.error.output" failonerror="false">
            <arg value="--silent" />
            <arg value="--show-error" />
            <arg value="--request" />
            <arg value="POST" />
            <arg value="--header" />
            <arg value="Authorization: Bearer ${central.bearer.token}" />
            <arg value="https://central.sonatype.com/api/v1/publisher/deployment/${central.deploymentId}" />
        </exec>
        <echo message="Publish requested for ${central.deploymentId}. Track final PUBLISHED status at https://central.sonatype.com/publishing/deployments" />
    </target>

    <target name="central-release" depends="central-publish" description="Full Central Publishing Portal release: package, upload, wait for validation, publish" />


    <property name="ivy.install.version" value="2.5.0" />
    <property name="ivy.jar.dir" value="${basedir}/ivy" />
    <property name="ivy.jar.file" value="${ivy.jar.dir}/ivy.jar" />

    <target name="check-download" >
        <available file="${ivy.jar.file}" property="skip.download"/>
    </target>

    <target name="download-ivy" depends="check-download" unless="skip.download">
        <mkdir dir="${ivy.jar.dir}"/>

        <echo message="installing ivy..."/>
        <get src="https://repo1.maven.org/maven2/org/apache/ivy/ivy/${ivy.install.version}/ivy-${ivy.install.version}.jar" dest="${ivy.jar.file}" usetimestamp="true"/>
    </target>

    <target name="setup-ivy" depends="download-ivy" description="--> setup ivy" unless="prepared">
        <path id="ivy.lib.path">
            <fileset dir="${ivy.jar.dir}" includes="*.jar"/>
        </path>
        <taskdef resource="org/apache/ivy/ant/antlib.xml" uri="antlib:org.apache.ivy.ant" classpathref="ivy.lib.path"/>
    </target>


    <target name="-version1" unless="version" >
        <mkdir dir="${dist.dir}/tmp" />
        <get src="https://api.github.com/repos/marc4j/marc4j/releases/latest" dest="${dist.dir}/tmp/git.release.txt" />
        <loadfile srcfile="${dist.dir}/tmp/git.release.txt" property="versionstr" >
            <filterchain>
                <tokenfilter>
                    <replacestring from="," to=",${line.separator}" />
                </tokenfilter>
                <linecontains>
                   <contains value="tag_name"/>
                </linecontains>
                <tokenfilter>
                     <replaceregex pattern=".*&quot;tag_name&quot;:[ ]*&quot;([0-9.]*).*" replace="\1" />
                </tokenfilter>
                <striplinebreaks/>
            </filterchain>
        </loadfile>
        <loadresource property="specversion">
          <propertyresource name="versionstr"/>
          <filterchain>
            <tokenfilter>
              <filetokenizer/>
              <replaceregex pattern="[.][0-9]*$" replace=""/>
            </tokenfilter>
          </filterchain>
        </loadresource>
        <echo message="specversion = ${specversion}" />
        <echo message="versionstr = ${versionstr}" />
    </target>

    <target name="-version2" unless="version" >
        <get src="https://api.github.com/repos/marc4j/marc4j/compare/${versionstr}...master" dest="${dist.dir}/tmp/git.commits.txt" />
        <loadfile srcfile="${dist.dir}/tmp/git.commits.txt" property="versionsuffix" >
            <filterchain>
                <tokenfilter>
                    <replacestring from="," to=", ${line.separator}" />
                </tokenfilter>
                <linecontains>
                   <contains value="total_commits"/>
                </linecontains>
                <striplinebreaks/>
                <tokenfilter>
                    <replaceregex pattern=".*&quot;total_commits&quot;:[ ]*([1-9][0-9]*).*" replace="-\1-SNAPSHOT" />
                    <replaceregex pattern=".*&quot;total_commits&quot;:[ ]*(0).*" replace="" />
                </tokenfilter>
            </filterchain>
        </loadfile>
        <echo message="versionsuffix = ${versionsuffix}" />
        <property name="versionsuffix" value="" />
        <echo message="versionsuffix = ${versionsuffix}" />
     <!--    <delete dir="${dist.dir}/tmp" /> -->
    </target>

    <available file=".git" type="dir" property="git.present"/>

    <target name="git.revision" description="Store git revision in ${repository.version}" if="git.present" unless="version">
        <property environment="env"/>
        <exec executable="git" outputproperty="git.revision" failifexecutionfails="false" errorproperty="git.not.found">
            <arg value="describe"/>
            <arg value="--tags"/>
            <arg value="--dirty=-SNAPSHOT"/>
            <arg value="--always"/>
        </exec>
        <exec executable="git" outputproperty="git.major.revision" failifexecutionfails="false" errorproperty="git.not.found">
            <arg value="describe"/>
            <arg value="--tags"/>
            <arg value="--abbrev=0"/>
        </exec>
        <condition property="version" value="${git.revision}">
            <and>
                <isset property="git.revision"/>
                <length string="${git.revision}" trim="yes" length="0" when="greater"/>
            </and>
        </condition>
        <condition property="versionstr" value="${git.major.revision}">
            <and>
                <isset property="git.major.revision"/>
                <length string="${git.major.revision}" trim="yes" length="0" when="greater"/>
            </and>
        </condition>
    </target>

    <target name="version" depends="git.revision,-version1,-version2" description="Get the version number to use from github" >
        <echo message="git.revision = ${git.revision}" />

        <property name="version" value="${versionstr}${versionsuffix}" />
        <echo message="version = ${version}" />
        <condition property="is.snapshot">
            <contains string="${version}" substring="SNAPSHOT" />
        </condition>
        <echo message="is.snapshot = ${is.snapshot}" />
        <property name="jar.name" value="${project.name}-${version}.jar" />
        <property name="jar.sources.name" value="${project.name}-${version}-sources.jar" />
        <property name="jar.javadoc.name" value="${project.name}-${version}-javadoc.jar" />
        <property name="test.jar.name" value="${project.name}_test-${version}.jar" />
    </target>


</project>
